ENV["VAGRANT_DEFAULT_PROVIDER"] = "vmware_desktop"

Vagrant.require_version ">= 2.3.0"

BOX_IMAGE = "bento/ubuntu-22.04"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE


  config.vm.define "webapp" do |subconfig|
    subconfig.vm.hostname = "webapp"

    subconfig.vm.network "forwarded_port",
    guest: 80,
    host: 8080,
    host_ip: "127.0.0.1",
    auto_correct: true

    subconfig.vm.network "forwarded_port",
    guest: 16686,
    host: 16686,
    host_ip: "127.0.0.1",
    auto_correct: true

    subconfig.vm.network "forwarded_port",
    guest: 4317,
    host: 4317,
    host_ip: "127.0.0.1",
    auto_correct: true

    subconfig.vm.network "forwarded_port",
    guest: 4318,
    host: 4318,
    host_ip: "127.0.0.1",
    auto_correct: true

    subconfig.vm.synced_folder ".", "/vagrant", disabled: true


    subconfig.vm.provider "vmware_desktop" do |v|
      v.cpus = 2
      v.memory = 4096

    end
  end
end
