extensions:
  jaeger_storage:
    backends:
      memstore:
        memory:
          max_traces: 100000

  jaeger_query:
    storage:
      traces: memstore
    base_path: /
    http:
      endpoint: 0.0.0.0:16686
    grpc:
      endpoint: 127.0.0.1:16685

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:14317
      http:
        endpoint: 127.0.0.1:14318

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: memstore

service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
